[package]
name = "candle-flashmla"
version.workspace = true
edition.workspace = true

[dependencies]
candle = { git = "https://github.com/mixlayer/candle", package = "candle-core", branch = "fix/add-i16-i32-cuda-kernels", features = ["cuda"] }
flashmla.workspace = true
float8 = { version = "0.6.0", features = ["cuda"] }
half = "2.4.1"
